<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : src/track.proto
 */


namespace Datlv\Ufms\RegVehicle;

/**
 * Protobuf enum : ufms.RegVehicle.VehicleType
 */
class VehicleType extends \Protobuf\Enum
{

    /**
     * Khach = 100
     */
    const Khach_VALUE = 100;

    /**
     * Bus = 200
     */
    const Bus_VALUE = 200;

    /**
     * HopDong = 300
     */
    const HopDong_VALUE = 300;

    /**
     * DuLich = 400
     */
    const DuLich_VALUE = 400;

    /**
     * Container = 500
     */
    const Container_VALUE = 500;

    /**
     * XeTai = 600
     */
    const XeTai_VALUE = 600;

    /**
     * Taxi = 700
     */
    const Taxi_VALUE = 700;

    /**
     * TaxiTai = 800
     */
    const TaxiTai_VALUE = 800;

    /**
     * XeDauKeo = 900
     */
    const XeDauKeo_VALUE = 900;

    /**
     * @var \Datlv\Ufms\RegVehicle\VehicleType
     */
    protected static $Khach = null;

    /**
     * @var \Datlv\Ufms\RegVehicle\VehicleType
     */
    protected static $Bus = null;

    /**
     * @var \Datlv\Ufms\RegVehicle\VehicleType
     */
    protected static $HopDong = null;

    /**
     * @var \Datlv\Ufms\RegVehicle\VehicleType
     */
    protected static $DuLich = null;

    /**
     * @var \Datlv\Ufms\RegVehicle\VehicleType
     */
    protected static $Container = null;

    /**
     * @var \Datlv\Ufms\RegVehicle\VehicleType
     */
    protected static $XeTai = null;

    /**
     * @var \Datlv\Ufms\RegVehicle\VehicleType
     */
    protected static $Taxi = null;

    /**
     * @var \Datlv\Ufms\RegVehicle\VehicleType
     */
    protected static $TaxiTai = null;

    /**
     * @var \Datlv\Ufms\RegVehicle\VehicleType
     */
    protected static $XeDauKeo = null;

    /**
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function Khach()
    {
        if (self::$Khach !== null) {
            return self::$Khach;
        }

        return self::$Khach = new self('Khach', self::Khach_VALUE);
    }

    /**
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function Bus()
    {
        if (self::$Bus !== null) {
            return self::$Bus;
        }

        return self::$Bus = new self('Bus', self::Bus_VALUE);
    }

    /**
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function HopDong()
    {
        if (self::$HopDong !== null) {
            return self::$HopDong;
        }

        return self::$HopDong = new self('HopDong', self::HopDong_VALUE);
    }

    /**
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function DuLich()
    {
        if (self::$DuLich !== null) {
            return self::$DuLich;
        }

        return self::$DuLich = new self('DuLich', self::DuLich_VALUE);
    }

    /**
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function Container()
    {
        if (self::$Container !== null) {
            return self::$Container;
        }

        return self::$Container = new self('Container', self::Container_VALUE);
    }

    /**
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function XeTai()
    {
        if (self::$XeTai !== null) {
            return self::$XeTai;
        }

        return self::$XeTai = new self('XeTai', self::XeTai_VALUE);
    }

    /**
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function Taxi()
    {
        if (self::$Taxi !== null) {
            return self::$Taxi;
        }

        return self::$Taxi = new self('Taxi', self::Taxi_VALUE);
    }

    /**
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function TaxiTai()
    {
        if (self::$TaxiTai !== null) {
            return self::$TaxiTai;
        }

        return self::$TaxiTai = new self('TaxiTai', self::TaxiTai_VALUE);
    }

    /**
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function XeDauKeo()
    {
        if (self::$XeDauKeo !== null) {
            return self::$XeDauKeo;
        }

        return self::$XeDauKeo = new self('XeDauKeo', self::XeDauKeo_VALUE);
    }

    /**
     * @param int $value
     * @return \Datlv\Ufms\RegVehicle\VehicleType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 100: return self::Khach();
            case 200: return self::Bus();
            case 300: return self::HopDong();
            case 400: return self::DuLich();
            case 500: return self::Container();
            case 600: return self::XeTai();
            case 700: return self::Taxi();
            case 800: return self::TaxiTai();
            case 900: return self::XeDauKeo();
            default: return null;
        }
    }


}

