<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : src/track.proto
 */


namespace Datlv\Ufms;

/**
 * Protobuf message : ufms.RegDriver
 */
class RegDriver extends \Protobuf\AbstractMessage implements \Protobuf\Extension
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * driver required string = 1
     *
     * @var string
     */
    protected $driver = null;

    /**
     * name optional string = 2
     *
     * @var string
     */
    protected $name = null;

    /**
     * datetimeIssue optional int32 = 3
     *
     * @var int
     */
    protected $datetimeIssue = null;

    /**
     * datetimeExpire optional int32 = 4
     *
     * @var int
     */
    protected $datetimeExpire = null;

    /**
     * regPlace optional string = 5
     *
     * @var string
     */
    protected $regPlace = null;

    /**
     * license optional string = 6
     *
     * @var string
     */
    protected $license = null;

    /**
     * Extension field : msg optional message = 410
     *
     * @var \Protobuf\Extension
     */
    protected static $msg = null;

    /**
     * Check if 'driver' has a value
     *
     * @return bool
     */
    public function hasDriver()
    {
        return $this->driver !== null;
    }

    /**
     * Get 'driver' value
     *
     * @return string
     */
    public function getDriver()
    {
        return $this->driver;
    }

    /**
     * Set 'driver' value
     *
     * @param string $value
     */
    public function setDriver($value)
    {
        $this->driver = $value;
    }

    /**
     * Check if 'name' has a value
     *
     * @return bool
     */
    public function hasName()
    {
        return $this->name !== null;
    }

    /**
     * Get 'name' value
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set 'name' value
     *
     * @param string $value
     */
    public function setName($value = null)
    {
        $this->name = $value;
    }

    /**
     * Check if 'datetimeIssue' has a value
     *
     * @return bool
     */
    public function hasDatetimeIssue()
    {
        return $this->datetimeIssue !== null;
    }

    /**
     * Get 'datetimeIssue' value
     *
     * @return int
     */
    public function getDatetimeIssue()
    {
        return $this->datetimeIssue;
    }

    /**
     * Set 'datetimeIssue' value
     *
     * @param int $value
     */
    public function setDatetimeIssue($value = null)
    {
        $this->datetimeIssue = $value;
    }

    /**
     * Check if 'datetimeExpire' has a value
     *
     * @return bool
     */
    public function hasDatetimeExpire()
    {
        return $this->datetimeExpire !== null;
    }

    /**
     * Get 'datetimeExpire' value
     *
     * @return int
     */
    public function getDatetimeExpire()
    {
        return $this->datetimeExpire;
    }

    /**
     * Set 'datetimeExpire' value
     *
     * @param int $value
     */
    public function setDatetimeExpire($value = null)
    {
        $this->datetimeExpire = $value;
    }

    /**
     * Check if 'regPlace' has a value
     *
     * @return bool
     */
    public function hasRegPlace()
    {
        return $this->regPlace !== null;
    }

    /**
     * Get 'regPlace' value
     *
     * @return string
     */
    public function getRegPlace()
    {
        return $this->regPlace;
    }

    /**
     * Set 'regPlace' value
     *
     * @param string $value
     */
    public function setRegPlace($value = null)
    {
        $this->regPlace = $value;
    }

    /**
     * Check if 'license' has a value
     *
     * @return bool
     */
    public function hasLicense()
    {
        return $this->license !== null;
    }

    /**
     * Get 'license' value
     *
     * @return string
     */
    public function getLicense()
    {
        return $this->license;
    }

    /**
     * Set 'license' value
     *
     * @param string $value
     */
    public function setLicense($value = null)
    {
        $this->license = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * Extension field : msg
     *
     * @return \Protobuf\Extension\ExtensionField
     */
    public static function msg()
    {
        if (self::$msg !== null) {
            return self::$msg;
        }

        $readCallback = function (\Protobuf\ReadContext $context, $wire) {
            $reader = $context->getReader();
            $length = $context->getLength();
            $stream = $context->getStream();

            \Protobuf\WireFormat::assertWireType($wire, 11);

            $innerSize    = $reader->readVarint($stream);
            $innerMessage = new \Ufms\RegDriver();

            $value = $innerMessage;

            $context->setLength($innerSize);
            $innerMessage->readFrom($context);
            $context->setLength($length);

            return $value;
        };

        $writeCallback = function (\Protobuf\WriteContext $context, $value) {
            $stream      = $context->getStream();
            $writer      = $context->getWriter();
            $sizeContext = $context->getComputeSizeContext();

            $writer->writeVarint($stream, 3282);
            $writer->writeVarint($stream, $value->serializedSize($sizeContext));
            $value->writeTo($context);
        };

        $sizeCallback = function (\Protobuf\ComputeSizeContext $context, $value) {
            $calculator = $context->getSizeCalculator();
            $size       = 0;

            $innerSize = $value->serializedSize($context);

            $size += 2;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);

            return $size;
        };

        return self::$msg = new \Protobuf\Extension\ExtensionField('\\Datlv\\Ufms\\BaseMessage', 'msg', 410, $readCallback, $writeCallback, $sizeCallback, __METHOD__);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['driver'])) {
            throw new \InvalidArgumentException('Field "driver" (tag 1) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'name' => null,
            'datetimeIssue' => null,
            'datetimeExpire' => null,
            'regPlace' => null,
            'license' => null
        ], $values);

        $message->setDriver($values['driver']);
        $message->setName($values['name']);
        $message->setDatetimeIssue($values['datetimeIssue']);
        $message->setDatetimeExpire($values['datetimeExpire']);
        $message->setRegPlace($values['regPlace']);
        $message->setLicense($values['license']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'RegDriver',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'driver',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'name',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'datetimeIssue',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'datetimeExpire',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'regPlace',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'license',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
            'extension' => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 410,
                    'name' => 'msg',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'extendee' => '.ufms.BaseMessage',
                    'type_name' => '.ufms.RegDriver'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->driver === null) {
            throw new \UnexpectedValueException('Field "\\Datlv\\Ufms\\RegDriver#driver" (tag 1) is required but has no value.');
        }

        if ($this->driver !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->driver);
        }

        if ($this->name !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->name);
        }

        if ($this->datetimeIssue !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->datetimeIssue);
        }

        if ($this->datetimeExpire !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->datetimeExpire);
        }

        if ($this->regPlace !== null) {
            $writer->writeVarint($stream, 42);
            $writer->writeString($stream, $this->regPlace);
        }

        if ($this->license !== null) {
            $writer->writeVarint($stream, 50);
            $writer->writeString($stream, $this->license);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->driver = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->name = $reader->readString($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->datetimeIssue = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->datetimeExpire = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->regPlace = $reader->readString($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->license = $reader->readString($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->driver !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->driver);
        }

        if ($this->name !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->name);
        }

        if ($this->datetimeIssue !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->datetimeIssue);
        }

        if ($this->datetimeExpire !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->datetimeExpire);
        }

        if ($this->regPlace !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->regPlace);
        }

        if ($this->license !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->license);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->driver = null;
        $this->name = null;
        $this->datetimeIssue = null;
        $this->datetimeExpire = null;
        $this->regPlace = null;
        $this->license = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Datlv\Ufms\RegDriver) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->driver = ($message->driver !== null) ? $message->driver : $this->driver;
        $this->name = ($message->name !== null) ? $message->name : $this->name;
        $this->datetimeIssue = ($message->datetimeIssue !== null) ? $message->datetimeIssue : $this->datetimeIssue;
        $this->datetimeExpire = ($message->datetimeExpire !== null) ? $message->datetimeExpire : $this->datetimeExpire;
        $this->regPlace = ($message->regPlace !== null) ? $message->regPlace : $this->regPlace;
        $this->license = ($message->license !== null) ? $message->license : $this->license;
    }


}

